// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBJ0m_By1VPmhT_QGdIwaSZzhnQ1LBWl8',
    appId: '1:76551612752:web:3895ee598b917a6d8b2455',
    messagingSenderId: '76551612752',
    projectId: 'familytree-3325e',
    authDomain: 'familytree-3325e.firebaseapp.com',
    storageBucket: 'familytree-3325e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5M0MQdFPQJpMn9ZWsy70jBlbyJCDfaKQ',
    appId: '1:76551612752:android:3813ca527cd7c4888b2455',
    messagingSenderId: '76551612752',
    projectId: 'familytree-3325e',
    storageBucket: 'familytree-3325e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkDlaM5MiXLJB6th-CPryTxWH_pthVyMU',
    appId: '1:76551612752:ios:4d98cdc4a994d7628b2455',
    messagingSenderId: '76551612752',
    projectId: 'familytree-3325e',
    storageBucket: 'familytree-3325e.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkDlaM5MiXLJB6th-CPryTxWH_pthVyMU',
    appId: '1:76551612752:ios:4d98cdc4a994d7628b2455',
    messagingSenderId: '76551612752',
    projectId: 'familytree-3325e',
    storageBucket: 'familytree-3325e.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBJ0m_By1VPmhT_QGdIwaSZzhnQ1LBWl8',
    appId: '1:76551612752:web:5eec5e2d9a3d31358b2455',
    messagingSenderId: '76551612752',
    projectId: 'familytree-3325e',
    authDomain: 'familytree-3325e.firebaseapp.com',
    storageBucket: 'familytree-3325e.firebasestorage.app',
  );
}
